[package]
name = "intermediate"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0.14"
reqwest = { version = "0.12.7", features = ["json"] }
serde_json = "1.0.127"
tokio = { version = "1.40.0", features = ["full"] }
